//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSentry.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceSentry.Common.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceSentry.
        /// </summary>
        internal static string _ApplicationName {
            get {
                return ResourceManager.GetString("_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auturge.
        /// </summary>
        internal static string _CompanyName {
            get {
                return ResourceManager.GetString("_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddMMMyyyy - HHmmss.
        /// </summary>
        internal static string Archive_DateTime {
            get {
                return ResourceManager.GetString("Archive_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling Stop: {0}.
        /// </summary>
        internal static string Debug_HandlingStop {
            get {
                return ResourceManager.GetString("Debug_HandlingStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string DefaultServiceGroupName {
            get {
                return ResourceManager.GetString("DefaultServiceGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquiring new client for service &apos;{0}&apos; on {1}..
        /// </summary>
        internal static string Error_AcquiringNewClient {
            get {
                return ResourceManager.GetString("Error_AcquiringNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Faulted.  Acquiring new client for service &apos;{0}&apos; on {1}..
        /// </summary>
        internal static string Error_CommunicationFaulted {
            get {
                return ResourceManager.GetString("Error_CommunicationFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not attach {0}.
        /// </summary>
        internal static string Error_CouldNotAttach1 {
            get {
                return ResourceManager.GetString("Error_CouldNotAttach1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  because it is being used by another process.
        /// </summary>
        internal static string Error_CouldNotAttach2 {
            get {
                return ResourceManager.GetString("Error_CouldNotAttach2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate client mediator for service {0}\{1}..
        /// </summary>
        internal static string Error_CouldNotGenerateClientMediator {
            get {
                return ResourceManager.GetString("Error_CouldNotGenerateClientMediator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: &quot;{0}&quot;.
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; service did not restart..
        /// </summary>
        internal static string Error_ServiceDidNotRestart {
            get {
                return ResourceManager.GetString("Error_ServiceDidNotRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; service is not {1}..
        /// </summary>
        internal static string Error_ServiceNotInDesiredStatus {
            get {
                return ResourceManager.GetString("Error_ServiceNotInDesiredStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; service NOT started..
        /// </summary>
        internal static string Error_ServiceNotStarted {
            get {
                return ResourceManager.GetString("Error_ServiceNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} service NOT started via local controller..
        /// </summary>
        internal static string Error_ServiceNotStartedLocally {
            get {
                return ResourceManager.GetString("Error_ServiceNotStartedLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} service NOT stopped via local controller..
        /// </summary>
        internal static string Error_ServiceNotStoppedLocally {
            get {
                return ResourceManager.GetString("Error_ServiceNotStoppedLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} service NOT stopped via Monitor service..
        /// </summary>
        internal static string Error_ServiceNotStoppedRemotely {
            get {
                return ResourceManager.GetString("Error_ServiceNotStoppedRemotely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; service not toggling: perhaps a prerequisite service is stopped?.
        /// </summary>
        internal static string Error_ServiceWontToggle {
            get {
                return ResourceManager.GetString("Error_ServiceWontToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find existing service in registry..
        /// </summary>
        internal static string EXCEPTION_CannotFindServiceInRegistry {
            get {
                return ResourceManager.GetString("EXCEPTION_CannotFindServiceInRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not invoke the &apos;GetInstance()&apos; method on type &apos;{0}&apos;..
        /// </summary>
        internal static string EXCEPTION_CouldNotGetInstance {
            get {
                return ResourceManager.GetString("EXCEPTION_CouldNotGetInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emailInfo.From cannot be null..
        /// </summary>
        internal static string EXCEPTION_FromCannotBeNull {
            get {
                return ResourceManager.GetString("EXCEPTION_FromCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ServiceControllerStatus..
        /// </summary>
        internal static string EXCEPTION_InvalidServiceControllerStatus {
            get {
                return ResourceManager.GetString("EXCEPTION_InvalidServiceControllerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ServiceState..
        /// </summary>
        internal static string EXCEPTION_InvalidServiceState {
            get {
                return ResourceManager.GetString("EXCEPTION_InvalidServiceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWindowsService cannot be null in call to WindowsServiceHarness.GetInstance()..
        /// </summary>
        internal static string EXCEPTION_IWindowsServiceCannotBeNull {
            get {
                return ResourceManager.GetString("EXCEPTION_IWindowsServiceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is empty..
        /// </summary>
        internal static string EXCEPTION_PathIsEmpty {
            get {
                return ResourceManager.GetString("EXCEPTION_PathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsServiceDescription serviceDescription must include a service type or a service object..
        /// </summary>
        internal static string EXCEPTION_ServiceDescriptionNeedsTypeOrObject {
            get {
                return ResourceManager.GetString("EXCEPTION_ServiceDescriptionNeedsTypeOrObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to install must implement a public static &apos;GetInstance()&apos; method which returns a class that inherits from WindowsService..
        /// </summary>
        internal static string EXCEPTION_ServiceMustBeAbstract {
            get {
                return ResourceManager.GetString("EXCEPTION_ServiceMustBeAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to install must be marked with a WindowsServiceAttribute..
        /// </summary>
        internal static string EXCEPTION_ServiceMustBeMarkedWithAttribute {
            get {
                return ResourceManager.GetString("EXCEPTION_ServiceMustBeMarkedWithAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to install must inherit from WindowsService..
        /// </summary>
        internal static string EXCEPTION_ServiceMustInheritWindowsService {
            get {
                return ResourceManager.GetString("EXCEPTION_ServiceMustInheritWindowsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTION encountered while stopping service: {0}.
        /// </summary>
        internal static string EXCEPTION_StoppingService {
            get {
                return ResourceManager.GetString("EXCEPTION_StoppingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTION: {0}.
        /// </summary>
        internal static string EXCEPTION_WithMessage {
            get {
                return ResourceManager.GetString("EXCEPTION_WithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Display Name: .
        /// </summary>
        internal static string Header_DisplayName {
            get {
                return ResourceManager.GetString("Header_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name: .
        /// </summary>
        internal static string Header_MachineName {
            get {
                return ResourceManager.GetString("Header_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name: .
        /// </summary>
        internal static string Header_ServiceName {
            get {
                return ResourceManager.GetString("Header_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp: .
        /// </summary>
        internal static string Header_TimeStamp {
            get {
                return ResourceManager.GetString("Header_TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing logs..
        /// </summary>
        internal static string Info_ClearingLogs {
            get {
                return ResourceManager.GetString("Info_ClearingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating archive: {0}.
        /// </summary>
        internal static string Info_CreatingArchive {
            get {
                return ResourceManager.GetString("Info_CreatingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string Info_Done {
            get {
                return ResourceManager.GetString("Info_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Client: Email Sent..
        /// </summary>
        internal static string INFO_EmailSent {
            get {
                return ResourceManager.GetString("INFO_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing log files are attached.
        /// </summary>
        internal static string Info_ExistingLogFilesAttached {
            get {
                return ResourceManager.GetString("Info_ExistingLogFilesAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring logs..
        /// </summary>
        internal static string Info_IgnoringLogs {
            get {
                return ResourceManager.GetString("Info_IgnoringLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;{0}&apos; service..
        /// </summary>
        internal static string Info_InstallingWindowsService {
            get {
                return ResourceManager.GetString("Info_InstallingWindowsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files are attached.
        /// </summary>
        internal static string Info_LogFilesAttached {
            get {
                return ResourceManager.GetString("Info_LogFilesAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger attached to service &apos;{0}&apos;..
        /// </summary>
        internal static string Info_LoggerAttachedToService {
            get {
                return ResourceManager.GetString("Info_LoggerAttachedToService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files were specified, but do not exist.
        /// </summary>
        internal static string Info_LogsDoNotExist {
            get {
                return ResourceManager.GetString("Info_LogsDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No log files were specified.
        /// </summary>
        internal static string Info_NoLogFilesSpecified {
            get {
                return ResourceManager.GetString("Info_NoLogFilesSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responding to stopped service: {0}.
        /// </summary>
        internal static string Info_RespondingToStoppedService {
            get {
                return ResourceManager.GetString("Info_RespondingToStoppedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send completed..
        /// </summary>
        internal static string Info_SendCompleted {
            get {
                return ResourceManager.GetString("Info_SendCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email to: &apos;{0}&apos;..
        /// </summary>
        internal static string Info_SendingEmail {
            get {
                return ResourceManager.GetString("Info_SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is already running: {0}.
        /// </summary>
        internal static string Info_ServiceAlreadyRunning {
            get {
                return ResourceManager.GetString("Info_ServiceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; service started..
        /// </summary>
        internal static string Info_ServiceStarted {
            get {
                return ResourceManager.GetString("Info_ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} service started via local controller..
        /// </summary>
        internal static string Info_ServiceStartedLocally {
            get {
                return ResourceManager.GetString("Info_ServiceStartedLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service stopped: {0}.
        /// </summary>
        internal static string Info_ServiceStopped {
            get {
                return ResourceManager.GetString("Info_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} service stopped via local controller..
        /// </summary>
        internal static string Info_ServiceStoppedLocally {
            get {
                return ResourceManager.GetString("Info_ServiceStoppedLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} service stopped via Monitor service..
        /// </summary>
        internal static string Info_ServiceStoppedRemotely {
            get {
                return ResourceManager.GetString("Info_ServiceStoppedRemotely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; service {1}stopped unexpectedly..
        /// </summary>
        internal static string Info_ServiceStoppedUnexpectedly {
            get {
                return ResourceManager.GetString("Info_ServiceStoppedUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;{0}&quot;) .
        /// </summary>
        internal static string Info_ServiceStoppedUnexpectedly1 {
            get {
                return ResourceManager.GetString("Info_ServiceStoppedUnexpectedly1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; service stopped unexpectedly on {1}.
        /// </summary>
        internal static string Info_ServiceStoppedUnexpectedlyOnMachine {
            get {
                return ResourceManager.GetString("Info_ServiceStoppedUnexpectedlyOnMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service: {0}.
        /// </summary>
        internal static string Info_StartingService {
            get {
                return ResourceManager.GetString("Info_StartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping service: {0}.
        /// </summary>
        internal static string Info_StoppingService {
            get {
                return ResourceManager.GetString("Info_StoppingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed to &apos;{0}&apos;..
        /// </summary>
        internal static string Info_Subscribed {
            get {
                return ResourceManager.GetString("Info_Subscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing to &apos;{0}&apos; service..
        /// </summary>
        internal static string Info_SubscribingToService {
            get {
                return ResourceManager.GetString("Info_SubscribingToService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription updated: {0}.
        /// </summary>
        internal static string Info_SubscriptionUpdated {
            get {
                return ResourceManager.GetString("Info_SubscriptionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribed from &apos;{0}&apos;..
        /// </summary>
        internal static string Info_Unsubscribed {
            get {
                return ResourceManager.GetString("Info_Unsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribing from &apos;{0}&apos; service..
        /// </summary>
        internal static string Info_UnsubscribingFromService {
            get {
                return ResourceManager.GetString("Info_UnsubscribingFromService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating subscription: {0}.
        /// </summary>
        internal static string Info_UpdatingSubscription {
            get {
                return ResourceManager.GetString("Info_UpdatingSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing config file: {0}.
        /// </summary>
        internal static string Info_WritingConfigFile {
            get {
                return ResourceManager.GetString("Info_WritingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string Noun_NoKey {
            get {
                return ResourceManager.GetString("Noun_NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Noun_Options {
            get {
                return ResourceManager.GetString("Noun_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Noun_SentenceTerminator {
            get {
                return ResourceManager.GetString("Noun_SentenceTerminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Noun_YesKey {
            get {
                return ResourceManager.GetString("Noun_YesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command name cannot be an empty string..
        /// </summary>
        internal static string RelayCommand_Command_name_cannot_be_an_empty_string {
            get {
                return ResourceManager.GetString("RelayCommand_Command_name_cannot_be_an_empty_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raising event &apos;{0}&apos;..
        /// </summary>
        internal static string Trace_RaisingEvent {
            get {
                return ResourceManager.GetString("Trace_RaisingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting TrackingObject key: &apos;{0}&apos;..
        /// </summary>
        internal static string Trace_SettingTrackingObjectKey {
            get {
                return ResourceManager.GetString("Trace_SettingTrackingObjectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive and Clear Logs.
        /// </summary>
        internal static string Verb_ArchiveAndClearLogs {
            get {
                return ResourceManager.GetString("Verb_ArchiveAndClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Logs.
        /// </summary>
        internal static string Verb_ArchiveLogs {
            get {
                return ResourceManager.GetString("Verb_ArchiveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Logs (do not clear).
        /// </summary>
        internal static string Verb_ArchiveLogsDoNotClear {
            get {
                return ResourceManager.GetString("Verb_ArchiveLogsDoNotClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Logs.
        /// </summary>
        internal static string Verb_ClearLogs {
            get {
                return ResourceManager.GetString("Verb_ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Logs (do not archive).
        /// </summary>
        internal static string Verb_ClearLogsDoNotArchive {
            get {
                return ResourceManager.GetString("Verb_ClearLogsDoNotArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        internal static string Verb_Exit {
            get {
                return ResourceManager.GetString("Verb_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Logs.
        /// </summary>
        internal static string Verb_IgnoreLogs {
            get {
                return ResourceManager.GetString("Verb_IgnoreLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ServiceSentry.
        /// </summary>
        internal static string Verb_OpenApplication {
            get {
                return ResourceManager.GetString("Verb_OpenApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart All Services.
        /// </summary>
        internal static string Verb_RestartAllServices {
            get {
                return ResourceManager.GetString("Verb_RestartAllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start All Services.
        /// </summary>
        internal static string Verb_StartAllServices {
            get {
                return ResourceManager.GetString("Verb_StartAllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop All Services.
        /// </summary>
        internal static string Verb_StopAllServices {
            get {
                return ResourceManager.GetString("Verb_StopAllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install this version anyway [{0}/{1}]?  .
        /// </summary>
        internal static string Warn_InstallAnyway {
            get {
                return ResourceManager.GetString("Warn_InstallAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed version is newer..
        /// </summary>
        internal static string Warn_InstalledVersionIsNewer {
            get {
                return ResourceManager.GetString("Warn_InstalledVersionIsNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received {0} exceptions from the monitor..
        /// </summary>
        internal static string Warn_ReceivedExceptionsFromMonitor {
            get {
                return ResourceManager.GetString("Warn_ReceivedExceptionsFromMonitor", resourceCulture);
            }
        }
    }
}
