//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSentry.Extensibility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceSentry.Extensibility.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceSentry.Agent.
        /// </summary>
        public static string _AgentServiceName {
            get {
                return ResourceManager.GetString("_AgentServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceSentry.
        /// </summary>
        public static string _ApplicationName {
            get {
                return ResourceManager.GetString("_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auturge.
        /// </summary>
        public static string _CompanyName {
            get {
                return ResourceManager.GetString("_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\Extensions.
        /// </summary>
        public static string _DefaultExtensionsSubfolder {
            get {
                return ResourceManager.GetString("_DefaultExtensionsSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating extensions..
        /// </summary>
        public static string Debug_ActivatingExtensions {
            get {
                return ResourceManager.GetString("Debug_ActivatingExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger configured..
        /// </summary>
        public static string Debug_LoggerConfigured {
            get {
                return ResourceManager.GetString("Debug_LoggerConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New logger initialized..
        /// </summary>
        public static string Debug_LoggerInitialized {
            get {
                return ResourceManager.GetString("Debug_LoggerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        public static string Error_FileDNE {
            get {
                return ResourceManager.GetString("Error_FileDNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist..
        /// </summary>
        public static string Error_FolderDNE {
            get {
                return ResourceManager.GetString("Error_FolderDNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI is invalid..
        /// </summary>
        public static string Error_InvalidURI {
            get {
                return ResourceManager.GetString("Error_InvalidURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter partialPaths is of type List&lt;string&gt;, but was passed with zero items..
        /// </summary>
        public static string Error_PartialPathsPassedWithNoItems {
            get {
                return ResourceManager.GetString("Error_PartialPathsPassedWithNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command name cannot be an empty string..
        /// </summary>
        public static string EXCEPTION_CommandNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("EXCEPTION_CommandNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename is null..
        /// </summary>
        public static string EXCEPTION_FilenameIsNull {
            get {
                return ResourceManager.GetString("EXCEPTION_FilenameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ordinal..
        /// </summary>
        public static string EXCEPTION_InvalidOrdinal {
            get {
                return ResourceManager.GetString("EXCEPTION_InvalidOrdinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogLevel does not exist: &apos;{0}&apos;.
        /// </summary>
        public static string EXCEPTION_LevelNotUnderstood {
            get {
                return ResourceManager.GetString("EXCEPTION_LevelNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogLevel is null..
        /// </summary>
        public static string EXCEPTION_LogLevelIsNull {
            get {
                return ResourceManager.GetString("EXCEPTION_LogLevelIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path directory is null..
        /// </summary>
        public static string EXCEPTION_PathDirectoryIsNull {
            get {
                return ResourceManager.GetString("EXCEPTION_PathDirectoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path root is null..
        /// </summary>
        public static string EXCEPTION_PathRootIsNull {
            get {
                return ResourceManager.GetString("EXCEPTION_PathRootIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown log level: {0}.
        /// </summary>
        public static string EXCEPTION_UnknownLogLevel {
            get {
                return ResourceManager.GetString("EXCEPTION_UnknownLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTION.
        /// </summary>
        public static string Header_Exception {
            get {
                return ResourceManager.GetString("Header_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Header_Message {
            get {
                return ResourceManager.GetString("Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack TRACE.
        /// </summary>
        public static string Header_StackTrace {
            get {
                return ResourceManager.GetString("Header_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string HeaderedProperty {
            get {
                return ResourceManager.GetString("HeaderedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string LogLevel_Debug {
            get {
                return ResourceManager.GetString("LogLevel_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LogLevel_Error {
            get {
                return ResourceManager.GetString("LogLevel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        public static string LogLevel_Fatal {
            get {
                return ResourceManager.GetString("LogLevel_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string LogLevel_Info {
            get {
                return ResourceManager.GetString("LogLevel_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string LogLevel_Off {
            get {
                return ResourceManager.GetString("LogLevel_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRACE.
        /// </summary>
        public static string LogLevel_TRACE {
            get {
                return ResourceManager.GetString("LogLevel_TRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn.
        /// </summary>
        public static string LogLevel_Warn {
            get {
                return ResourceManager.GetString("LogLevel_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Noun_EllipsisChars {
            get {
                return ResourceManager.GetString("Noun_EllipsisChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file.
        /// </summary>
        public static string Verb_CopyFile {
            get {
                return ResourceManager.GetString("Verb_CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder.
        /// </summary>
        public static string Verb_OpenContainingFolder {
            get {
                return ResourceManager.GetString("Verb_OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ServiceSentry.
        /// </summary>
        public static string Warden_BaseAddress {
            get {
                return ResourceManager.GetString("Warden_BaseAddress", resourceCulture);
            }
        }
    }
}
